# Generated by Django 2.0.4 on 2018-04-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Unnamed', max_length=120)),
                ('Age', models.IntegerField(blank=True, default=0)),
                ('genderChoice', models.CharField(blank=True, max_length=10, null=True)),
                ('Opno', models.IntegerField(blank=True, default=0)),
                ('Ipno', models.IntegerField(blank=True, default=0)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Phoneno', models.IntegerField(blank=True, default=0)),
                ('Kureid', models.CharField(blank=True, max_length=10, null=True)),
                ('ChiefComplaints', models.CharField(blank=True, max_length=120, null=True)),
                ('Historyofillness', models.TextField(blank=True, null=True)),
                ('PastHistory', models.TextField(blank=True, null=True)),
                ('Familyhistory', models.TextField(blank=True, null=True)),
                ('Medicationhistroy', models.TextField(blank=True, null=True)),
                ('Alcohol', models.BooleanField(default=False)),
                ('Smoking', models.BooleanField(default=False)),
                ('Bowel', models.BooleanField(default=False)),
                ('Bladder', models.BooleanField(default=False)),
                ('Sleep', models.BooleanField(default=False)),
                ('Summary', models.TextField(blank=True, null=True)),
                ('Examinedby', models.CharField(blank=True, max_length=10, null=True)),
                ('Verifiedby', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='newModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
