# Generated by Django 2.0.3 on 2018-04-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
