# Generated by Django 2.0.5 on 2018-05-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='Section4Name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
