# Generated by Django 2.0.4 on 2018-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='Historyofillness',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[0][PastHistory]',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newmodel',
            name='age',
            field=models.ManyToManyField(to='webapp.formModel'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Kureid',
            field=models.CharField(default='hedUmaqXnfdPHrlm8QcEjbTmn9Z0IaPr', max_length=120),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='PastHistory',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='genderChoice',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
