# Generated by Django 2.0.4 on 2018-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='Age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='genderChoice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
