# Generated by Django 2.0.4 on 2018-04-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180414_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='ABCleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='ABCright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='AbdomenLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='AbdomenRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Abdominalleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Abdominalright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Ankleleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Ankleright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Appearance',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='BCleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='BCright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='CVSleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='CVSright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Clubbing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='ColorVisionLeft',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='ColorVisionRIght',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Comealexpressionleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Comealexpressionright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='ConsensualLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='ConsensualRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Cremastricleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Cremastricright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Cyanosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Diastolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='DirectLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='DirectRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Emotion',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='ExtensionLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='ExtensionRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='EyeResponse',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='FieldLeft',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='FieldRight',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Fingerflexionleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Fingerflexionright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='FlexionLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='FlexionRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='FundusLeft',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='FundusRight',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='GagRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Gagleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='GeneralCondiotions',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='HOffmansLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='HOffmansRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Handedness',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='HangGripleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='HangGripright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Ictreus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='JPSleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='JPSright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Kneeleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Kneeright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Lightreflexleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Lightreflexright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Lymphadenopathy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='MMSE',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Memory',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='MotorResponse',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='MovemenstLeft',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='MovemenstRight',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='NHISscore',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='NeurocutaneousMarkers',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='NystagmusLeft',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='NystagmusRight',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='OlfactoryLeft',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='OlfactoryRight',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Orientation',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Palar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='PittingEdema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='PlantarLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='PlantarRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='PulseRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='PupilLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='PupilRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='RespiratoryRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='SensoryLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='SensoryRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='SkeletalExamination',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='SpontaneosSpeech',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='SubcutaneousMarkers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Systolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='VerbalResponse',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='VisualAcuityLeft',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='VisualAcuityRight',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='abductionleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='abductionleft1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='abductionright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='abductionright1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='abnormalmovementsright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='abornmalmovementsleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='accomodationLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='accomodationRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='adductionleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='adductionleft1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='adductionright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='adductionright1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='bicepsleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='bicepsright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='bulkleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='bulkright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='comealreflexleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='comealreflexright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='ehlleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='ehlright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='eversionleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='eversionright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='extensionleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='extensionleft1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='extensionleft2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='extensionleft3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='extensionleft4',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='extensionright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='extensionright1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='extensionright2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='extensionright3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='extensionright4',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='eyeclosesureleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='eyeclosesureright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='facialexpressionsleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='facialexpressionsright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='fingerNoseTextleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='fingerNoseTextright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='flexionleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='flexionleft1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='flexionleft2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='flexionleft3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='flexionleft4',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='flexionright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='flexionright1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='flexionright2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='flexionright3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='flexionright4',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='inversionleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='inversionright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='jawjerkleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='jawjerkright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='kneeHelltestleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='kneeHelltestright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='lowerLimbleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='lowerLimbleft1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='lowerLimbright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='lowerLimbright1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='motorLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='motorLeft1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='motorRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='motorRight1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='nystagmusleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='nystagmusright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='othersLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='othersRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='palatalleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='palatalright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='pectoralLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='pectoralRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='pendularKneeJerkleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='pendularKneeJerkright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='poweroftongueleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='poweroftongueright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='protrusionleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='protrusionright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='respiratorSystemleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='respiratorSystemright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='rhombusleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='rhombusright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='rinnesleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='rinnesright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='rombersLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='rombersRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='scmleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='scmright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='sensoryLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='sensoryLeft1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='sensoryRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='sensoryRight1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='shoulderleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='shoulderright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='supinatorleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='supinatorright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='tasteleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='tasteright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='toneleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='toneleft1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='toneright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='toneright1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='trapeziusleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='trapeziusright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='tricepsleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='tricepsright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='trunkleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='trunkright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='upperlimbleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='upperlimbleft1',
            field=models.CharField(max_length=102, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='upperlimbright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='upperlimbright1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='uvulaleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='uvularight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='vibrationLeft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='vibrationRight',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='wastingleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='wastingright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='webbersleft',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='webbersright',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
