# Generated by Django 2.0.4 on 2018-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180410_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='PastHistory',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='Historyofillness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Kureid',
            field=models.CharField(default='bjXb8UwIjmOSxSuGaRU8UuKEXsOKd2rJ', max_length=120),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='[0][PastHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
