# Generated by Django 2.0.5 on 2018-05-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180512_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='webbersleft',
            new_name='webbers',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='webbersright',
        ),
    ]
