# Generated by Django 2.0.4 on 2018-04-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180427_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='GeneralCondiotions',
            new_name='Built',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='GeneralConditions',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
