# Generated by Django 2.0.4 on 2018-04-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180410_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='Kureid',
            field=models.CharField(default='FDWvrilHRcoNmeq4Ti5wcr5WQ1bMwKTP', max_length=120),
        ),
    ]
