# Generated by Django 2.0.4 on 2018-04-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180410_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='Familyhistory',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[0][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[10][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[1][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[2][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[3][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[4][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[5][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[6][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[7][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[8][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='[9][FamilyHistory]',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Kureid',
            field=models.CharField(default='CV8Yx5FPXbhGqrjM1gNOWqfDgK6zGjuX', max_length=120),
        ),
        migrations.DeleteModel(
            name='newModel',
        ),
    ]
