# Generated by Django 2.0.5 on 2018-05-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180512_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='protrusionleft',
            new_name='protrusion',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='protrusionright',
        ),
    ]
