# Generated by Django 2.0.5 on 2018-05-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180512_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='rombersLeft',
            new_name='rombers',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='rombersRight',
        ),
    ]
