# Generated by Django 2.0.5 on 2018-05-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180513_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='trunkleft1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='trunkright1',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
