# Generated by Django 2.0.4 on 2018-04-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180410_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='[0][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[10][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[1][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[2][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[3][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[4][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[5][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[6][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[7][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[8][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[9][PastHistory]',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='PastHistory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Kureid',
            field=models.CharField(default='KgaX5ZNeuGoBi6gEuHOsvzmTHZ44avjl', max_length=120),
        ),
    ]
