# Generated by Django 2.0.5 on 2018-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180602_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='SubcutaneousMarkers',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
