# Generated by Django 2.0.4 on 2018-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180412_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='[0][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[0][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[10][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[10][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[1][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[1][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[2][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[2][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[3][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[3][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[4][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[4][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[5][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[5][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[6][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[6][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[7][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[7][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[8][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[8][PastHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[9][FamilyHistory]',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='[9][PastHistory]',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='FamilyHistory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='PastHistory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Kureid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Phoneno',
            field=models.IntegerField(blank=True),
        ),
    ]
