# Generated by Django 2.0.5 on 2018-06-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180622_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='Kureid',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
    ]
