# Generated by Django 2.0.5 on 2018-06-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180627_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='ABCleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='ABCright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Appearance',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Built',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='ChiefComplaints',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='ColorVisionLeft',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='ColorVisionRIght',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Comealexpressionleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Comealexpressionright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='ConsensualLeft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='ConsensualRight',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='DirectLeft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='DirectRight',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Emotion',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Examinedby',
            field=models.CharField(blank=True, default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='ExtensionLeft12',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='ExtensionRight12',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='EyeResponse',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='FamilyHistory',
            field=models.CharField(blank=True, default='None', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='FieldLeft',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='FieldRight',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='FlexionLeft12',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='FlexionRight12',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='FundusLeft',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='FundusRight',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='GagRight',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Gagleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='GeneralConditions',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Handedness',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Historyofillness',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Lightreflexleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Lightreflexright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='MMSE',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Medicationhistroy',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Memory',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='MotorResponse',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='MovemenstLeft',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='MovemenstRight',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='NHISscore',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='NeurocutaneousMarkers',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='NystagmusLeft',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='NystagmusRight',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='OlfactoryLeft',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='OlfactoryRight',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Orientation',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='PastHistory',
            field=models.CharField(blank=True, default='None', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='ProvisionalDiagnosis',
            field=models.CharField(blank=True, default='None', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='PupilLeft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='PupilRight',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='SensoryLeft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='SensoryRight',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='SkeletalExamination',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='SpontaneosSpeech',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='SubcutaneousMarkers',
            field=models.CharField(blank=True, default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Summary',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='VerbalResponse',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='Verifiedby',
            field=models.CharField(blank=True, default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='VisualAcuityLeft',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='VisualAcuityRight',
            field=models.CharField(blank=True, default='None', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='abductionleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='abductionright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='accomodationLeft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='accomodationRight',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='adductionleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='adductionright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='bulkleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='bulkright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='comealreflexleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='comealreflexright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='extensionleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='extensionleft1',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='extensionright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='extensionright1',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='eyeclosesureleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='eyeclosesureright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='facialexpressionsleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='facialexpressionsright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='flexionleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='flexionleft1',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='flexionright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='flexionright1',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='jawjerk',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='motorLeft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='motorLeft1',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='motorRight',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='motorRight1',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='nystagmusleft12',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='nystagmusright12',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='palatalleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='palatalright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='poweroftongueleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='poweroftongueright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='protrusion',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='rhombusleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='rhombusright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='rinnesleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='rinnesright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='scmleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='scmright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='sensoryLeft1',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='sensoryLeft12',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='sensoryRight1',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='sensoryRight12',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='shoulderleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='shoulderright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='tasteleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='tasteright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='toneleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='toneright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='trapeziusleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='trapeziusright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='uvula',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='wastingleft',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='wastingright',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='webbers',
            field=models.CharField(blank=True, default='None', max_length=120, null=True),
        ),
    ]
