# Generated by Django 2.0.5 on 2018-06-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20180627_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='Temperature',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
